package pacman

const (
	HeaderFilename     = "FILENAME"
	HeaderName         = "NAME"
	HeaderBase         = "BASE"
	HeaderVersion      = "VERSION"
	HeaderDescription  = "DESC"
	HeaderCSize        = "CSIZE"
	HeaderISize        = "ISIZE"
	HeaderSize         = "SIZE"
	HeaderMD5Sum       = "MD5SUM"
	HeaderSha256Sum    = "SHA256SUM"
	HeaderPGPSignature = "PGPSIG"
	HeaderURL          = "URL"
	HeaderValidation   = "VALIDATION"
	HeaderLicense      = "LICENSE"
	HeaderArch         = "ARCH"
	HeaderBuildDate    = "BUILDDATE"
	HeaderInstallDate  = "INSTALLDATE"
	HeaderPackager     = "PACKAGER"
	HeaderReason       = "REASON"
	HeaderGroups       = "GROUPS"
	HeaderConflicts    = "CONFLICTS"
	HeaderReplaces     = "REPLACES"
	HeaderProvides     = "PROVIDES"
	HeaderDepends      = "DEPENDS"
	HeaderMakeDepends  = "MAKEDEPENDS"
	HeaderOptDepends   = "OPTDEPENDS"
	HeaderCheckDepends = "CHECKDEPENDS"
	HeaderXData        = "XDATA"
)
